# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=200)),
                ('cooked_date', models.DateTimeField(verbose_name='date cooked')),
                ('slices', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=200)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboard.Pizza')),
            ],
        ),
    ]
